#!/bin/bash

#------------------------------------------------------------------------------
# Startup script for strBridge
#
# chkconfig: 345 85 15
# description: A high-performance UDP packet reflector.
# processname: strBridge
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Source function library:
#------------------------------------------------------------------------------

. /etc/rc.d/init.d/functions

#------------------------------------------------------------------------------
# Globals:
#------------------------------------------------------------------------------

PID_FILE=/var/run/strBridge.pid

#------------------------------------------------------------------------------
# Entry point:
#------------------------------------------------------------------------------

case "$1" in

	#------------------
	# Start strBridge:
	#------------------

	start)

		action "Starting strBridge: " /usr/bin/strBridge
		exit $?
		;;

	#-----------------
	# Stop strBridge:
	#-----------------

	stop)

		action "Stopping strBridge: " /usr/bin/kill -9 `cat $PID_FILE`
		rm $PID_FILE
		exit $?
		;;

	#--------------------
	# Restart strBridge:
	#--------------------

	restart)

		$0 stop
		$0 start
		;;

	#------------
	# Catch-all:
	#------------

	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac